name: Add Review Label

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  add-label:
    runs-on: ubuntu-latest
    
    steps:
      - name: Add pending review label
        if: github.event.issue.number
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: ['pending-review']
            })