name: Issue Labeler
on:
  issues:
    types: [opened]
  workflow_dispatch:
    inputs:
      issue_number:
        description: 'Issue number to label'
        required: true
        type: number

jobs:
  label-new-issues:
    runs-on: ubuntu-latest
    if: github.repository == 'THOR-Collective/HEARTH'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
             const issueNumber = context.eventName === 'workflow_dispatch' 
              ? context.payload.inputs.issue_number
              : context.payload.issue?.number;
            
              console.log('Processing issue:', issueNumber);
            
              try {
                const issue = await github.rest.issues.get({
                  owner: context.repo.owner || 'THOR-Collective',
                  repo: context.repo.name || 'HEARTH',
                  issue_number: parseInt(issueNumber)
                });
                
                const defaultLabels = ['pending-review'];
                if (issue.data.body) {
                  const match = issue.data.body.match(/### Hunt Type 🔥\s*\n\n([^\n]+)/);
                  if (match) {
                    if (match[1].includes('Flames')) defaultLabels.push('hypothesis-driven');
                    if (match[1].includes('Embers')) defaultLabels.push('baseline');
                    if (match[1].includes('Alchemy')) defaultLabels.push('model-assisted');
                  }
                }
                
                await github.rest.issues.addLabels({
                  owner: context.repo.owner || 'THOR-Collective',
                  repo: context.repo.name || 'HEARTH', 
                  issue_number: parseInt(issueNumber),
                  labels: defaultLabels
                });
              } catch (error) {
                console.error(`Error processing issue #${issueNumber}:`, error);
              }
