name: Issue Labeler
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  label-new-issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Label issues based on template
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const defaultLabels = ['pending-review'];
            
            // Parse the issue body to get the hunt type
            const issueBody = issue.body;
            const huntTypeMatch = issueBody.match(/### Hunt Type 🔥\s*\n\s*(Flames|Embers|Alchemy)/);
            
            if (huntTypeMatch) {
              const huntType = huntTypeMatch[1];
              
              // Add labels based on hunt type
              if (huntType.includes('Flames')) {
                defaultLabels.push('hypothesis-driven');
              } else if (huntType.includes('Embers')) {
                defaultLabels.push('baseline');
              } else if (huntType.includes('Alchemy')) {
                defaultLabels.push('model-assisted');
              }
            }
            
            // Add labels to the issue
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.name,
              issue_number: issue.number,
              labels: defaultLabels
            });
