name: Issue Labeler
on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  label-new-issues:
    runs-on: ubuntu-latest
    if: github.repository == 'THOR-Collective/HEARTH'
    steps:
      - uses: actions/github-script@v7
        with:
          script: |
            console.log('Event:', context.eventName);
            console.log('Action:', context.payload.action);
            console.log('Payload:', JSON.stringify(context.payload));
            
            const issue = context.payload.issue;
            if (!issue) {
              console.log('No issue data found');
              return;
            }

            const defaultLabels = ['pending-review'];
            
            try {
              // Look for hunt type in form response
              const formMatch = issue.body?.match(/### Hunt Type 🔥\s*\n\n([^\n]+)/);
              if (formMatch) {
                const huntType = formMatch[1];
                console.log('Found hunt type:', huntType);
                
                if (huntType.includes('Flames')) {
                  defaultLabels.push('hypothesis-driven');
                } else if (huntType.includes('Embers')) {
                  defaultLabels.push('baseline');
                } else if (huntType.includes('Alchemy')) {
                  defaultLabels.push('model-assisted');
                }
              }

              console.log('Adding labels:', defaultLabels);
              await github.rest.issues.addLabels({
                owner: 'THOR-Collective',
                repo: 'HEARTH',
                issue_number: issue.number,
                labels: defaultLabels
              });
            } catch (error) {
              console.log('Error:', error);
              console.log('Issue body:', issue.body);
            }
