name: Add Review Label

on:
  issues:
    types: [opened]
  workflow_dispatch:

jobs:
  add-label:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    
    steps:
      - name: Add pending review label
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          script: |
            github.rest.issues.addLabels({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: ['pending-review']
            })